### ISSUE TITLE
Reusing opened connections 

### ISSUE THREAD

**Issue by aashishgoyal** [JuliaWeb/Requests.jl#107]
Is there a way to reuse connections opened to the same server, just as a session object in python requests allows. This could greatly speeds up consecutive api hits to a server. From what I gather this library primarily provides a stateless interface.

**Comment by malmaud** [comment]
This would be a good thing to have.

**Comment by ninjin** [comment]
Looking over the code and the commits I think this feature request is still outstanding, but implementing it does not look too tricky.  Seconding the request since reusing a connection is essential not to tick off REST API maintainers.  I may have a look if I can contribute, but I am a bit strapped for time at the moment.

**Comment by quinnj** [comment]
FWIW, this is implemented in HTTP.jl already. It's getting pretty close to a v0.1.

**Comment by rahulkp220** [comment]
Something like a `requests.Session()` objects in the python requests lib would be awesome.

**Comment by malmaud** [comment]
Probably no one is going to add new features to this package now that HTTP.jl is out.

**Comment by ararslan** [comment]
We should probably do formal deprecations of Requests, HttpServer, and the like.
