### ISSUE TITLE
Requests package for Julia v0.4

### ISSUE THREAD

**Issue by silenj** [JuliaWeb/Requests.jl#71]
Failure of getting the finished flag field:
e.g.

using Requests
z=Requests.get("http://valid url/")

ERROR: type Response has no field finished
 in on_message_complete at /.julia/v0.4/Requests/src/Requests.jl:219

Regards Johan

**Comment by sebastiang** [comment]
There is a commit apparently meant to fix this (https://github.com/JuliaWeb/HttpCommon.jl/commit/101a72f78048f5ee49783d8a4cf7821eefdc483a) but standard package updating doesn't fetch the newer version because the pull request to `METADATA` hasn't been accepted yet. (https://github.com/JuliaLang/METADATA.jl/pull/3330). At that point, a `Pkg.update()` will fix the problem. In the meantime, you will need to clone the latest `HttpCommon.jl`

**Comment by malmaud** [comment]
It's merged now, so a `Pkg.update()` will fix the problem. Sorry for the inconvenience.
